# Generated by Django 3.1.7 on 2021-03-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('province', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
            ],
        ),
    ]
