# Generated by Django 3.1.7 on 2021-03-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_economy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='universities',
            field=models.ManyToManyField(null=True, to='restApi.University'),
        ),
    ]
